---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"

exclude_paths: []
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - app/**
  - "**.js"

exclude_paths:
- bin/**/*
